### ISSUE TITLE
Bitcoin Satellite cannot be built on a 32-bit Debian

### ISSUE THREAD

**Issue by VDelport** [Blockstream/bitcoinsatellite#1]
Hello, I'm trying to build your version of Bitcoin Fibre, which you call Bitcoin Satellite, on a 32-bit computer with a Debian operating system (4.9.0-9-686-pae # 1 SMP Debian 4.9.168-1 + deb9u3 (2019-06-16) i686 GNU / Linux).

I get the following error message:

In file included from wirehair / gf256.h: 70: 0,
from wirehair / gf256.cpp: 30:
/usr/lib/gcc/i686-linux-gnu/6/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ’_m128i mm_shuffle_epi8 ( m128i, __m128i)’: target specific option mismatch
_mm_shuffle_epi8 (__m128i __X, __m128i __Y)

What compiler options do I need to use to configure the build process?

By the way, this error does not occur when creating the original version of Bitcoin Fibre.

**Comment by blockstreamsatellite** [comment]
Hi @VDelport , thanks for moving the issue to this repository. 

We will let you know once we are able to try the compilation on architecture i686 with a Debian distribution. We have not tried this combination yet. Also, we currently support Ubuntu, Fedora, and CentOS only.

Note that there are a few definitions on `gf256.h` to activate SIMD usage, but at this point (without trying) it's hard to say exactly what you need. For example, to build for `aarch64`, we use `CXXFLAGS` with `-DLINUX_ARM -DHAVE_ARM_NEON_H`, like so:

```
make CXXFLAGS='-pipe -O2 -fvisibility=hidden -DLINUX_ARM -DHAVE_ARM_NEON_H'
```

FYI, we have recently prepared binary packages for the distributions that we support at the moment. Please, refer to the instructions that were just posted at: https://github.com/Blockstream/satellite/blob/master/doc/bitcoin.md#from-binary-packages. The Ubuntu packages, in particular, are built for the following architectures: `amd64` (x86_64), `aarch64`, `armhf`, and `i386`.

We'll go ahead and close the original issue at https://github.com/Blockstream/satellite/issues/54. And we'll leave this open until we are able to try Debian i686.

**Comment by blockstreamsatellite** [comment]
Hi @VDelport ,

Not sure if you are still interested in running on Debian i386. For you, or anybody else interested, note that we support the installation on Debian and Raspberry Pi OS since release 0.4.0 of the Blocksat CLI (see the [changelog](https://github.com/Blockstream/satellite/blob/master/CHANGELOG.md#040)). We have packages for the amd64, arm64, armhf, and i386 architectures. For example, see the [package repository for Debian Bullseye](https://aptly.blockstream.com/satellite/debian/dists/bullseye/main/).

So, since version 0.4.0, you can simply use the CLI to install dependencies on Debian. More specifically, you can run the command below (refer to the [user guide](https://blockstream.github.io/satellite/doc/software.html)):

```
blocksat-cli deps install
```

We are closing this issue now.

Please feel free to get in touch any time.
