### ISSUE TITLE
Installation of bitcoin satellite on a 64-bit Ubuntu VERSION 20.04.3 LTS failed

### ISSUE THREAD

**Issue by VDelport** [Blockstream/bitcoinsatellite#6]
Hello, I tried to install Bitcoin Satellite on a 64-bit Ubuntu VERSION 20.04.3 LTS (Focal Fossa). Neither the package installation nor the installation after compiling the sources works. That means when I run bitcoind I get" Illegal instruction (core dumped) ". Is there an option to configure the compilation process that solves this problem? 

For which Ubuntu LTS version does Bitcoin Satellite work? 

Maybe the problem is not the Ubuntu version but the CPU? 
model name      : Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz

After running bitcoind with the gdb debugger, I get the following output:
(gdb) run
Starting program: / usr / local / bin / bitcoind
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
gf256_mul_mem_init () at wirehair / gf256.cpp: 581
581 const GF256_M128 table_lo = _mm_loadu_si128 ((GF256_M128 *) lo);

**Comment by blockstreamsatellite** [comment]
Hi @VDelport ,

Can you check if your CPU supports SSE3? You can check by running `lscpu | grep sse3`.

**Comment by VDelport** [comment]
Thank you for your response. According to lscpu | grep sse3 I get this output:
Flags: fpu ... ssse3 ...

**Comment by blockstreamsatellite** [comment]
Thanks for confirming, @VDelport . Could you also confirm the CPU architecture (the full `lscpu` output would help) and the package version you are trying to run? Are you using the latest package, `0.21.1.0.2.2-0ppa1~ubuntu20.04`?

For reference, the most recent version prints the following version:
```
> bitcoind --version | head -1
Bitcoin Core version v0.21.1.0-gbcd42982f1562ea80a6f674b40870c568348bc40
```

If you can't run `bitcoind` because it crashes, you can check the package version with:

```
apt list --installed | grep bitcoin-satellite
```

Regarding the problem, it's hard to say exactly what it is at this point. It's certainly related to the CPU (the available SIMD instruction set), not the package itself. Let's try to collect some extra information.

We have solved some issues related to sse2/sse3/avx2 intrinsics some time ago in commit https://github.com/Blockstream/bitcoinsatellite/commit/617145742d619a69cbe906cc8f1f3ff2979dc0b4, which is available since the `0.21.1.0.2.1` release. Maybe there is still something missing in there to properly detect when the CPU does not support SSE2 or SSE3 (which are the sets containing the failing [_mm_loadu_si128 instruction](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_loadu_si128&expand=4195,4335)).

If you try to compile from source, we would be interested in taking a look at the intrinsics options printed by the end of the `configure` step, like the following:

```
Intrinsics Options:
  sse3          = yes
  sse41         = yes
  avx2          = yes
  shani         = yes
  neon          = no
```

**Comment by VDelport** [comment]
Thank you for your response.

lscpu | grep sse3
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d

apt list --installed | grep bitcoin-satellite
bitcoin-satellite-qt/focal,now 0.21.1.0.2.2-0ppa1~ubuntu20.04 amd64 [installed]
bitcoin-satellite-tx/focal,now 0.21.1.0.2.2-0ppa1~ubuntu20.04 amd64 [installed]

./configure --disable-wallet --without-gui
…
Intrinsics Options:
  sse3          = yes
  sse41         = yes
  avx2          = yes
  shani         = yes
  neon          = no

**Comment by blockstreamsatellite** [comment]
Hi @VDelport ,

Apologies for the long delay, and many thanks for sharing the information above.

We've investigated the problem and concluded it arises specifically when the CPU can compile AVX2 code but not actually run it. Note the `Intrinsics Options` you shared above, which lists AVX2 as available. On the other hand, note the `lscpu` flags, which do not include AVX2.

We are working on a solution that will come in the next Bitcoin Satellite release soon. In the meantime, you can try compiling from source using branch `ssse3_gf256`, as follows:

```
git clone https://github.com/Blockstream/bitcoinsatellite.git
cd bitcoinsatellite
git checkout ssse3_gf256
./autogen.sh
./configure
make # use "-j N" for N parallel jobs
make install # optional
```

The referred branch (`ssse3_gf256`) is minimally tested at this point. We would appreciate if you could try it and confirm that it solves the problem. Alternatively, if it doesn't work, you can try the simpler workaround available on branch `disable_avx`. To do so, repeat some of the compilation steps as follows:

```
git checkout ssse3_gf256
./configure
make # use "-j N" for N parallel jobs
make install # optional
```

Lastly, here is a brief explanation about the problem for your information:

The problem was particularly on the `gf256.cpp` source used by the FEC libraries, as you can see in the original logs. This gf256 module detects in runtime whether the CPU supports AVX2 and other SIMD instruction sets. So, in your case, it would detect the absence of AVX2 in runtime and skip those calls. That was good, but it turns out that it wasn't enough. When the gf256 code is compiled with AVX2 flags (enabled by the `configure` step), the compilation can optimize other unintended parts of the code using AVX2 instructions. That was the case of the `_mm_loadu_si128` instruction, reported in the original logs. `_mm_loadu_si128` is an SSE2 instruction (supported by your CPU), but the compiler optimized it using AVX2 instructions instead. As a result, you got SIGILL when the application executed this function.

On branch `ssse3_gf256`, there is a better separation in the compilation steps. More information is available on commit 90582d206bb89c1c7c9b1d62daf35e8e43f9f4f5. So it should avoid the problem. If not, let us know, and we can make further changes.

Thanks for your patience.

**Comment by VDelport** [comment]
Great. I started bitcoinsatellite and started synchronizing the blockchain via the Internet, i.e. not via UDP and blockstream satellite. It runs. :)
Thank you for the patch.

**Comment by blockstreamsatellite** [comment]
Excellent! Thank you very much for confirming.

Please feel free to reopen the issue if you have any problems when trying the UDP satellite reception. We will close it for now.

Regards
